import {useState} from 'react';
import {AreaChart,Area,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid} from 'recharts';
const num=n=>typeof n==='number'?new Intl.NumberFormat('en-GB',{maximumFractionDigits:1}).format(n):'—';
const money=n=>typeof n==='number'?new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(n):'—';
const label=value=>new Date(value).toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:'UTC'});
export default function OwnerCharts({insights,overall,loading}){
  const [period,setPeriod]=useState('daily'),[metric,setMetric]=useState('calls');
  const rows=insights?.[period]||[],sum=rows.reduce((total,row)=>total+row[metric],0);
  const conversion=insights&&overall?.totalCall>0?insights.orders.total/overall.totalCall*100:null;
  return <div className="co-charts"><section className="co-panel co-chart-panel"><div className="co-chart-heading"><div><h3>{metric==='calls'?'Call activity':'Call duration'}</h3><p>{period==='daily'?'Last 28 days':'Last 12 weeks · weeks start Monday'} · UTC</p></div><div className="co-chart-controls"><select aria-label="Chart metric" value={metric} onChange={e=>setMetric(e.target.value)}><option value="calls">Calls</option><option value="minutes">Minutes</option></select><div className="co-segment" role="group" aria-label="Chart period"><button aria-pressed={period==='daily'} onClick={()=>setPeriod('daily')}>Daily</button><button aria-pressed={period==='weekly'} onClick={()=>setPeriod('weekly')}>Weekly</button></div></div></div>
    <div className="co-chart-total"><strong>{insights?num(sum):'—'}</strong><span>{metric} in this view</span></div>
    <div className="co-chart">{insights?<ResponsiveContainer width="100%" height="100%"><AreaChart data={rows} margin={{top:10,right:10,left:-15,bottom:0}}><defs><linearGradient id="owner-call-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2563eb" stopOpacity={.3}/><stop offset="100%" stopColor="#2563eb" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#302e36" strokeDasharray="3 5"/><XAxis dataKey="date" tickFormatter={label} tick={{fill:'#a4a1aa',fontSize:10}} minTickGap={24} axisLine={false} tickLine={false}/><YAxis allowDecimals={metric==='minutes'} tick={{fill:'#a4a1aa',fontSize:10}} axisLine={false} tickLine={false}/><Tooltip labelFormatter={value=>(period==='weekly'?'Week of ':'')+label(value)} formatter={value=>[num(value),metric==='calls'?'Calls':'Minutes']} contentStyle={{background:'#201e24',border:'1px solid #39373f',borderRadius:8,color:'#fff'}}/><Area type="monotone" dataKey={metric} stroke="#2563eb" strokeWidth={2.5} fill="url(#owner-call-fill)" isAnimationActive={false}/></AreaChart></ResponsiveContainer>:<div className="co-chart-empty">{loading?'Loading your call history…':'Call history is unavailable. Please refresh.'}</div>}</div><p className="co-chart-note">{insights&&sum===0?'No recorded activity in this view. ':''}The current day or week is still in progress.</p></section>
    <section className="co-panel co-overall"><h3>Overall report</h3><p>All-time business performance</p><dl><div><dt>Average order value</dt><dd>{money(insights?.orders.average)}</dd></div><div><dt>Orders today</dt><dd>{num(insights?.orders.today)}</dd></div><div><dt>Failed calls</dt><dd>{num(insights?.failedCalls)}</dd></div><div><dt>Average call duration</dt><dd>{overall?.totalCall>0?num(overall.totalCallDuration/overall.totalCall)+' min':'—'}</dd></div><div><dt>Orders per 100 calls</dt><dd>{num(conversion)}</dd></div></dl><p className="co-chart-note">Order values use recorded prices in GBP, as in your order list. They do not confirm payment. {insights?.orders.unpriced>0?insights.orders.unpriced+' unpriced orders are excluded from value and average.':'Average order value uses priced orders.'}</p></section></div>;
}
