import {useState} from 'react';
import {Link} from 'react-router-dom';
import {Radio,Bot,Building2,RefreshCw} from 'lucide-react';

const duration=(start,now)=>{if(!start)return '—';const seconds=Math.max(0,Math.floor((now-Date.parse(start))/1000));return Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');};
export default function LiveUsage({live}) {
  const [tenant,setTenant]=useState('all');
  const rows=(live.data?.calls||[]).filter(call=>tenant==='all'||call.tenantId===tenant||(tenant==='unlinked'&&!call.tenantId));
  const status=live.isLoading?'Connecting':!live.fresh?'Updates unavailable':!live.data.complete?'Partial live data':'Live';
  const value=key=>live.reliable?live.data.summary[key]:live.fresh?live.data.summary[key]+' observed':'—';
  return <section className="ca-panel ca-live-panel" aria-label="Live agent usage">
    <div className="ca-panel-heading"><div><div className="ca-eyebrow"><span className="ca-live-dot"/>{status.toUpperCase()}</div><h2>Live agent usage</h2><p>Who is on a call right now · refreshes every 5 seconds</p></div><button className="ca-button" disabled={live.isFetching} onClick={()=>live.refetch()}><RefreshCw size={14} className={live.isFetching?'ca-spin':''}/>Refresh live</button></div>
    <div className="ca-live-metrics"><div><Radio size={19}/><span>Concurrent calls<strong>{value('activeCalls')}</strong></span></div><div><Bot size={19}/><span>Agents in use<strong>{value('agentsInUse')}</strong></span></div><div><Building2 size={19}/><span>Tenants on calls<strong>{value('tenantsInUse')}</strong></span></div><div className="ca-live-status"><span>{live.fresh?live.data.summary.ringing:'—'} ringing</span><span>{live.fresh?live.data.summary.queued:'—'} queued</span><span>{live.fresh?live.data.summary.forwarding:'—'} forwarded</span></div></div>
    {!live.fresh&&!live.isLoading&&<p className="ca-error" role="alert">Live updates are unavailable. The last snapshot below is not a current concurrency count.</p>}
    {live.fresh&&!live.data.complete&&<p className="ca-notice">A provider report is incomplete or unavailable. Counts show observed activity, and may be lower than actual usage.</p>}
    <div className="ca-live-toolbar"><span>{live.data?'Snapshot '+new Date(live.data.generatedAt).toLocaleTimeString('en-GB'):'Waiting for provider data'} · independent of date filters</span><select aria-label="Filter live usage by tenant" value={tenant} onChange={event=>setTenant(event.target.value)}><option value="all">All tenants</option>{live.data?.tenants.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}<option value="unlinked">Unlinked activity</option></select></div>
    <div className="ca-table-scroll"><table className="ca-table"><thead><tr><th>Tenant</th><th>Agent in use</th><th>Status</th><th>Live duration</th><th>Provider / call</th></tr></thead><tbody>{rows.map(call=><tr key={call.provider+':'+call.id}><td>{call.tenantId?<Link className="ca-tenant-link" to={'/admin/tenant-management/view/'+call.tenantId}>{call.tenantName}</Link>:<strong>Unlinked tenant</strong>}<small>{call.attribution==='current_agent'?'Assigned assistant match':call.attribution==='unlinked'?'No verified tenant link':'Recorded tenant link'}</small></td><td><strong>{call.agentName}</strong><small>{call.agentId||'Transient assistant'}</small></td><td><span className={'ca-status '+(call.status==='in-progress'&&live.fresh?'good':'neutral')}><i/>{call.status==='in-progress'?'On call':call.status}</span>{!live.fresh&&<small>Last known status</small>}</td><td>{duration(call.startedAt,live.fresh?live.now:Date.parse(live.data.generatedAt))}</td><td>{call.provider==='vapi'?'Vapi':'Calai Vapi'}<small>{call.id}</small></td></tr>)}</tbody></table></div>
    {!rows.length&&<div className="ca-live-empty"><Radio size={22}/><div><strong>{live.isLoading?'Checking active calls…':live.reliable?'No calls in progress'+(tenant==='all'?'':' for this tenant'): 'Live activity cannot be confirmed'}</strong><p>Tenant and agent details appear here automatically when a call starts.</p></div></div>}
    <p className="ca-panel-note">One agent can handle multiple concurrent calls. Only connected voice providers are covered; transferred calls are listed separately. {live.data?.summary.unlinkedActiveCalls>0?live.data.summary.unlinkedActiveCalls+' active calls still need a tenant link.':''}</p>
  </section>;
}
